# Application
spring.application.name=SmsGateway
spring.profiles.active=dev

# Server
server.port=8070
server.servlet.context-path=/api

spring.jpa.properties.hibernate.jdbc.time_zone=UTC
# Jackson
spring.jackson.time-zone=UTC
spring.jackson.default-property-inclusion=non_null

# Logging
logging.level.root=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n


# ==================== SWAGGER/OPENAPI ====================

# Activer Swagger UI
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.show-extensions=true
springdoc.swagger-ui.show-common-extensions=true

# Documentation OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
springdoc.packages-to-scan=TNB.SmsGateway.controller
springdoc.paths-to-match=/v1/**

# Groupes de endpoints
springdoc.group-configs[0].group=auth
springdoc.group-configs[0].paths-to-match=/v1/auth/**

springdoc.group-configs[1].group=webhook
springdoc.group-configs[1].paths-to-match=/v1/webhook/**

springdoc.group-configs[2].group=api-keys
springdoc.group-configs[2].paths-to-match=/v1/api-keys/**

springdoc.group-configs[3].group=devices
springdoc.group-configs[3].paths-to-match=/v1/devices/**

springdoc.group-configs[4].group=messages
springdoc.group-configs[4].paths-to-match=/v1/messages/**

springdoc.group-configs[5].group=coverage
springdoc.group-configs[5].paths-to-match=/v1/coverage/**

springdoc.group-configs[6].group=reference
springdoc.group-configs[6].paths-to-match=/v1/reference/**

springdoc.group-configs[7].group=health
springdoc.group-configs[7].paths-to-match=/v1/health/**

# Cache
springdoc.cache.disabled=false

# springdoc.api-docs.enabled=false
# springdoc.swagger-ui.enabled=false